$ErrorActionPreference = "Stop"

function Assert-FileContains {
    param(
        [string]$Path,
        [string]$Text
    )

    if (!(Test-Path $Path)) {
        throw "Missing required file: $Path"
    }

    $content = Get-Content $Path -Raw
    if (!$content.Contains($Text)) {
        throw "Missing marker '$Text' in $Path"
    }
}

Assert-FileContains "PosCore\Security\PosVersioningReleaseManifestBaseline.cs" "PosVersioningReleaseManifestBaseline"
Assert-FileContains "PosCore\Security\PosVersioningReleaseManifestBaseline.cs" "POS Versioning and Release Manifest Baseline"
Assert-FileContains "PosCore\Security\PosVersioningReleaseManifestBaseline.cs" "versioning and release manifest baseline documented"
Assert-FileContains "PosCore\Security\PosVersioningReleaseManifestBaseline.cs" "PHASE 8B release artifact inventory prerequisite documented"
Assert-FileContains "PosCore\Security\PosVersioningReleaseManifestBaseline.cs" "400 tests passed source evidence documented"
Assert-FileContains "PosCore\Security\PosVersioningReleaseManifestBaseline.cs" "405 tests expected after versioning manifest verification documented"
Assert-FileContains "PosCore\Security\PosVersioningReleaseManifestBaseline.cs" "semantic version format documented"
Assert-FileContains "PosCore\Security\PosVersioningReleaseManifestBaseline.cs" "release channel documented"
Assert-FileContains "PosCore\Security\PosVersioningReleaseManifestBaseline.cs" "build number source documented"
Assert-FileContains "PosCore\Security\PosVersioningReleaseManifestBaseline.cs" "commit sha source documented"
Assert-FileContains "PosCore\Security\PosVersioningReleaseManifestBaseline.cs" "artifact manifest template documented"
Assert-FileContains "PosCore\Security\PosVersioningReleaseManifestBaseline.cs" "manifest checksum field documented"
Assert-FileContains "PosCore\Security\PosVersioningReleaseManifestBaseline.cs" "manifest artifact path field documented"
Assert-FileContains "PosCore\Security\PosVersioningReleaseManifestBaseline.cs" "manifest created at field documented"
Assert-FileContains "PosCore\Security\PosVersioningReleaseManifestBaseline.cs" "manifest generated by field documented"
Assert-FileContains "PosCore\Security\PosVersioningReleaseManifestBaseline.cs" "no checkout behavior change"
Assert-FileContains "PosCore\Security\PosVersioningReleaseManifestBaseline.cs" "no inventory mutation"
Assert-FileContains "PosCore\Security\PosVersioningReleaseManifestBaseline.cs" "no production sync enablement"
Assert-FileContains "PosCore\Security\PosVersioningReleaseManifestBaseline.cs" "no packaging execution"
Assert-FileContains "PosCore\Security\PosVersioningReleaseManifestBaseline.cs" "no installer execution"
Assert-FileContains "PosCore\Security\PosVersioningReleaseManifestBaseline.cs" "no deployment execution"
Assert-FileContains "PosCore\Security\PosVersioningReleaseManifestBaseline.cs" "no schema change"
Assert-FileContains "PosCore\Security\PosVersioningReleaseManifestBaseline.cs" "no migrations"

Assert-FileContains "docs\POS_VERSIONING_RELEASE_MANIFEST_BASELINE.md" "versioning and release manifest baseline documented"
Assert-FileContains "docs\POS_VERSIONING_RELEASE_MANIFEST_BASELINE.md" "PHASE 8B release artifact inventory prerequisite documented"
Assert-FileContains "docs\POS_VERSIONING_RELEASE_MANIFEST_BASELINE.md" "semantic version format documented"
Assert-FileContains "docs\POS_VERSIONING_RELEASE_MANIFEST_BASELINE.md" "artifact manifest template documented"
Assert-FileContains "docs\POS_VERSIONING_RELEASE_MANIFEST_BASELINE.md" "manifest checksum field documented"
Assert-FileContains "docs\PHASE_8C_VERSIONING_RELEASE_MANIFEST_BASELINE.md" "405 tests passed"
Assert-FileContains "docs\PHASE_8C_VERSIONING_RELEASE_MANIFEST_BASELINE.md" "0 Advertencia(s)"
Assert-FileContains "docs\PHASE_8C_VERSIONING_RELEASE_MANIFEST_BASELINE.md" "0 Errores"
Assert-FileContains "docs\PROJECT_PROGRESS_REPORT_PHASE_8C.md" "20% -> 30%"
Assert-FileContains "docs\PROJECT_PROGRESS_REPORT_PHASE_8C.md" "Release Packaging and Operational Readiness"

Assert-FileContains "README.md" "PHASE 8C"
Assert-FileContains "README.md" "Versioning and Release Manifest Baseline"
Assert-FileContains "README.md" "405 tests passed"
Assert-FileContains "ROADMAP_FINALIZACION_POS_ACTUALIZADO.md" "PHASE 8C"
Assert-FileContains "ROADMAP_FINALIZACION_POS_ACTUALIZADO.md" "Versioning and Release Manifest Baseline"
Assert-FileContains "ROADMAP_FINALIZACION_POS_ACTUALIZADO.md" "Release Packaging and Operational Readiness: 20% -> 30%"
Assert-FileContains "PosInfrastructure.Tests\Architecture\InventoryLedgerConcurrencyBaselineTests.cs" "PosVersioningReleaseManifestBaseline_Should_Define_Versioning_And_Manifest_Checks"
Assert-FileContains "PosInfrastructure.Tests\Architecture\InventoryLedgerConcurrencyBaselineTests.cs" "Phase8C_Documentation_Should_Describe_Versioning_And_Release_Manifest_Baseline"
Assert-FileContains "PosInfrastructure.Tests\Architecture\InventoryLedgerConcurrencyBaselineTests.cs" "VerifyPhase8C_Should_Require_Versioning_Release_Manifest_Markers"

Write-Host "PHASE 8C markers verified."
